"""Promptfoo YAML exporter (§9 week-3 deliverable).

Maps each §3.3 invariant type to a Promptfoo assertion type:

  ordering        → tool-call-sequence  (custom javascript assertion)
  conditional     → contains  / regex   (with custom condition)
  negative        → not-contains
  statistical     → latency / cost      (or javascript for thresholds)
  output_format   → llm-rubric          (LLM-as-judge — already promptfoo-native)
  tool_selection  → contains
  state           → javascript
  composition     → javascript

We emit a self-contained YAML file the user can drop into a promptfoo
project. The generator stays template-driven: adding a new assertion type
means adding one row in the dispatch table.
"""

from __future__ import annotations

from typing import Any, Iterable

from latentspec.models.invariant import InvariantType
from latentspec.schemas.invariant import MinedInvariant


_HEADER = """\
# Generated by LatentSpec — do not edit by hand.
# `latentspec export-promptfoo --agent-id <id> > promptfoo.yaml`
"""


def export_promptfoo(
    invariants: Iterable[MinedInvariant],
    *,
    description: str = "LatentSpec discovered behavioral rules",
    provider: str = "anthropic:messages:claude-sonnet-4-5",
    prompt_template: str = "{{user_input}}",
) -> str:
    """Render a list of invariants as a Promptfoo YAML config string."""
    invariants = [inv for inv in invariants if inv.params or inv.description]
    test_blocks: list[str] = []
    for inv in invariants:
        block = _render_test_block(inv)
        if block:
            test_blocks.append(block)

    yaml = [
        _HEADER.rstrip(),
        f"description: {_yaml_str(description)}",
        f"providers:",
        f"  - {provider}",
        "prompts:",
        f"  - {_yaml_str(prompt_template)}",
        "tests:",
    ]
    if not test_blocks:
        yaml.append("  []")
    else:
        for block in test_blocks:
            yaml.append(block)
    return "\n".join(yaml) + "\n"


def _render_test_block(inv: MinedInvariant) -> str:
    p = dict(inv.params or {})
    label = inv.description.replace('"', "'")[:160]

    if inv.type == InvariantType.ORDERING:
        tool_a = p.get("tool_a", "?")
        tool_b = p.get("tool_b", "?")
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {
                    "type": "javascript",
                    "value": _js_ordering(tool_a, tool_b),
                }
            ],
        )

    if inv.type == InvariantType.CONDITIONAL:
        keyword = p.get("keyword", "")
        tool = p.get("tool", "")
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            vars={"keyword": keyword, "expected_tool": tool},
            assertions=[
                {
                    "type": "javascript",
                    "value": _js_conditional(keyword, tool),
                }
            ],
        )

    if inv.type == InvariantType.NEGATIVE:
        patterns = p.get("forbidden_patterns") or []
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {
                    "type": "not-contains-any",
                    "value": list(patterns),
                }
            ],
        )

    if inv.type == InvariantType.STATISTICAL:
        if p.get("metric") == "latency_ms":
            threshold = p.get("threshold") or 1000
            return _block(
                label,
                severity=inv.severity.value,
                inv_type=inv.type.value,
                assertions=[
                    {"type": "latency", "threshold": int(threshold)},
                ],
            )
        if p.get("metric") == "success_rate":
            return _block(
                label,
                severity=inv.severity.value,
                inv_type=inv.type.value,
                assertions=[
                    {
                        "type": "javascript",
                        "value": _js_success_rate(p.get("tool", ""), float(p.get("rate") or 0.95)),
                    }
                ],
            )

    if inv.type == InvariantType.OUTPUT_FORMAT:
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {
                    "type": "llm-rubric",
                    "value": inv.description,
                }
            ],
        )

    if inv.type == InvariantType.TOOL_SELECTION:
        tool = p.get("tool", "")
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {"type": "javascript", "value": _js_tool_used(tool)},
            ],
        )

    if inv.type in (InvariantType.STATE, InvariantType.COMPOSITION):
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {"type": "llm-rubric", "value": inv.description},
            ],
        )

    return ""


# ----- YAML helpers --------------------------------------------------------


def _yaml_str(value: str) -> str:
    if any(ch in value for ch in ":#\n\"'"):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def _block(
    label: str,
    *,
    severity: str,
    inv_type: str,
    vars: dict[str, Any] | None = None,
    assertions: list[dict[str, Any]] | None = None,
) -> str:
    lines = [
        f"  - description: {_yaml_str(label)}",
        f"    metadata:",
        f"      latentspec_severity: {severity}",
        f"      latentspec_type: {inv_type}",
    ]
    if vars:
        lines.append("    vars:")
        for k, v in vars.items():
            lines.append(f"      {k}: {_yaml_str(str(v))}")
    if assertions:
        lines.append("    assert:")
        for a in assertions:
            lines.append(f"      - type: {a['type']}")
            for key, val in a.items():
                if key == "type":
                    continue
                if isinstance(val, list):
                    lines.append(f"        {key}:")
                    for item in val:
                        lines.append(f"          - {_yaml_str(str(item))}")
                elif isinstance(val, str) and "\n" in val:
                    lines.append(f"        {key}: |")
                    for vl in val.splitlines():
                        lines.append(f"          {vl}")
                else:
                    lines.append(f"        {key}: {_yaml_str(str(val))}")
    return "\n".join(lines)


# ----- JavaScript assertion bodies -----------------------------------------


def _js_ordering(tool_a: str, tool_b: str) -> str:
    return (
        "(output, context) => {\n"
        f"  const a = {tool_a!r}; const b = {tool_b!r};\n"
        "  const calls = (context.toolCalls || context.tools || []);\n"
        "  let aIdx = -1, bIdx = -1;\n"
        "  calls.forEach((c, i) => {\n"
        "    if (aIdx === -1 && c.tool === a) aIdx = i;\n"
        "    if (bIdx === -1 && c.tool === b) bIdx = i;\n"
        "  });\n"
        "  if (bIdx === -1) return { pass: true, score: 1, reason: 'B not invoked (n/a)' };\n"
        "  if (aIdx === -1 || aIdx > bIdx) return { pass: false, score: 0, reason: `${a} did not precede ${b}` };\n"
        "  return { pass: true, score: 1 };\n"
        "}"
    )


def _js_conditional(keyword: str, tool: str) -> str:
    return (
        "(output, context) => {\n"
        f"  const kw = {keyword!r}; const t = {tool!r};\n"
        "  const userInput = (context.vars && context.vars.user_input) || '';\n"
        "  if (!userInput.toLowerCase().includes(kw)) return { pass: true, score: 1, reason: 'precondition not met' };\n"
        "  const calls = (context.toolCalls || context.tools || []);\n"
        "  if (calls.some(c => c.tool === t)) return { pass: true, score: 1 };\n"
        "  return { pass: false, score: 0, reason: `keyword '${kw}' present but tool '${t}' not invoked` };\n"
        "}"
    )


def _js_success_rate(tool: str, rate: float) -> str:
    return (
        "(output, context) => {\n"
        f"  const t = {tool!r}; const minRate = {rate};\n"
        "  const calls = (context.toolCalls || context.tools || []).filter(c => c.tool === t);\n"
        "  if (!calls.length) return { pass: true, score: 1, reason: 'tool not invoked (n/a)' };\n"
        "  const ok = calls.filter(c => (c.result_status || 'success') === 'success').length;\n"
        "  const observed = ok / calls.length;\n"
        "  return { pass: observed >= minRate, score: observed,\n"
        "           reason: `${t} success rate ${(observed*100).toFixed(1)}% vs target ${(minRate*100).toFixed(0)}%` };\n"
        "}"
    )


def _js_tool_used(tool: str) -> str:
    return (
        "(output, context) => {\n"
        f"  const t = {tool!r};\n"
        "  const calls = (context.toolCalls || context.tools || []);\n"
        "  return { pass: calls.some(c => c.tool === t), score: 1 };\n"
        "}"
    )
