"""Promptfoo YAML exporter (§9 week-3 deliverable).

Maps each §3.3 invariant type to a Promptfoo assertion type:

  ordering        → tool-call-sequence  (custom javascript assertion)
  conditional     → contains  / regex   (with custom condition)
  negative        → not-contains
  statistical     → latency / cost      (or javascript for thresholds)
  output_format   → llm-rubric          (LLM-as-judge — already promptfoo-native)
  tool_selection  → contains
  state           → javascript
  composition     → javascript

We emit a self-contained YAML file the user can drop into a promptfoo
project. The generator stays template-driven: adding a new assertion type
means adding one row in the dispatch table.
"""

from __future__ import annotations

from typing import Any, Iterable

from latentspec.models.invariant import InvariantType
from latentspec.schemas.invariant import MinedInvariant


_HEADER = """\
# Generated by LatentSpec — do not edit by hand.
# `latentspec export-promptfoo --agent-id <id> > promptfoo.yaml`
"""


def export_promptfoo(
    invariants: Iterable[MinedInvariant],
    *,
    description: str = "LatentSpec discovered behavioral rules",
    provider: str = "anthropic:messages:claude-sonnet-4-5",
    prompt_template: str = "{{user_input}}",
) -> str:
    """Render a list of invariants as a Promptfoo YAML config string."""
    invariants = [inv for inv in invariants if inv.params or inv.description]
    test_blocks: list[str] = []
    for inv in invariants:
        block = _render_test_block(inv)
        if block:
            test_blocks.append(block)

    yaml = [
        _HEADER.rstrip(),
        f"description: {_yaml_str(description)}",
        f"providers:",
        f"  - {provider}",
        "prompts:",
        f"  - {_yaml_str(prompt_template)}",
        "tests:",
    ]
    if not test_blocks:
        yaml.append("  []")
    else:
        for block in test_blocks:
            yaml.append(block)
    return "\n".join(yaml) + "\n"


def _render_test_block(inv: MinedInvariant) -> str:
    p = dict(inv.params or {})
    label = inv.description.replace('"', "'")[:160]

    if inv.type == InvariantType.ORDERING:
        tool_a = p.get("tool_a", "?")
        tool_b = p.get("tool_b", "?")
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {
                    "type": "javascript",
                    "value": _js_ordering(tool_a, tool_b),
                }
            ],
        )

    if inv.type == InvariantType.CONDITIONAL:
        keyword = p.get("keyword", "")
        tool = p.get("tool", "")
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            vars={"keyword": keyword, "expected_tool": tool},
            assertions=[
                {
                    "type": "javascript",
                    "value": _js_conditional(keyword, tool),
                }
            ],
        )

    if inv.type == InvariantType.NEGATIVE:
        patterns = p.get("forbidden_patterns") or []
        return _block(
            label,
            severity=inv.severity.value,
            inv_type=inv.type.value,
            assertions=[
                {
                    "type": "not-contains-any",
                    "value": list(patterns),
                }
            ],
        )

    if inv.type == InvariantType.STATISTICAL:
        if p.get("metric") == "latency_ms":
            threshold = p.get("threshold") or 1000
            return _block(
                label,
                severity=inv.severity.value,
                inv_type=inv.type.value,
                assertions=[
                    {"type": "latency", "threshold": int(threshold)},
                ],
            )
        if p.get("metric") == "success_rate":
            return _block(
                label,
                severity=inv.severity.value,
                inv_type=inv.type.value,
                assertions=[
                    {
                        "type": "javascript",
                        "value": _js_success_rate(p.get("tool", ""), float(p.get("rate") or 0.95)),
                    }
                ],
            )

    if inv.type == InvariantType.OUTPUT_FORMAT:
