"""Tests for the Promptfoo YAML exporter (§9 week-3)."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from latentspec.exporters import export_promptfoo
from latentspec.models.invariant import InvariantStatus, InvariantType, Severity
from latentspec.schemas.invariant import MinedInvariant


def _inv(type_: InvariantType, *, params: dict, description: str = "rule") -> MinedInvariant:
    return MinedInvariant(
        invariant_id=f"inv-{uuid.uuid4().hex[:8]}",
        type=type_,
        description=description,
        formal_rule="placeholder",
        confidence=0.95,
        support_score=0.9,
        consistency_score=0.95,
        cross_val_bonus=0.2,
        clarity_score=0.8,
        evidence_count=42,
        violation_count=0,
        discovered_at=datetime.now(UTC),
        status=InvariantStatus.ACTIVE,
        severity=Severity.HIGH,
        discovered_by="both",
        params=params,
    )


def test_export_emits_yaml_header_and_tests() -> None:
    invs = [
        _inv(
            InvariantType.ORDERING,
            params={"tool_a": "auth", "tool_b": "db_write"},
            description="Agent always calls `auth` before `db_write`",
        ),
        _inv(
            InvariantType.CONDITIONAL,
            params={"keyword": "refund", "tool": "escalate_human"},
            description="When user mentions 'refund', call escalate_human",
        ),
    ]
    yaml = export_promptfoo(invs)
    assert yaml.startswith("# Generated by LatentSpec")
    assert "providers:" in yaml
    assert "tests:" in yaml
    assert "auth" in yaml
    assert "escalate_human" in yaml
    # JS assertion bodies should be present
    assert "context.toolCalls" in yaml


def test_export_handles_each_supported_type() -> None:
    invs = [
        _inv(InvariantType.ORDERING, params={"tool_a": "a", "tool_b": "b"}),
        _inv(InvariantType.CONDITIONAL, params={"keyword": "k", "tool": "t"}),
        _inv(
            InvariantType.NEGATIVE,
            params={"forbidden_patterns": ["delete", "drop"]},
        ),
        _inv(
            InvariantType.STATISTICAL,
            params={"metric": "latency_ms", "tool": "search", "threshold": 500},
        ),
        _inv(
            InvariantType.STATISTICAL,
            params={"metric": "success_rate", "tool": "book", "rate": 0.99},
        ),
        _inv(InvariantType.OUTPUT_FORMAT, params={}, description="response is professional"),
    ]
    yaml = export_promptfoo(invs)
    assert yaml.count("- description:") == len(invs)
    assert "not-contains-any" in yaml
    assert "type: latency" in yaml
    assert "llm-rubric" in yaml


def test_export_with_no_invariants_still_valid() -> None:
    yaml = export_promptfoo([])
    assert "tests:" in yaml
    # An empty tests list is rendered explicitly so the YAML stays valid.
    assert "[]" in yaml
