"""Differential tests — production checker vs reference implementation.

For every (spec, trace) generated by Hypothesis we compute both outcomes
and assert they match. Disagreements indicate a bug in one of the two
implementations.
"""

from __future__ import annotations

from hypothesis import given, settings, HealthCheck

from latentspec.checking import dispatch
from latentspec.checking.base import CheckerError, CheckOutcome
from latentspec.checking.runner import check_trace
from latentspec.models.invariant import InvariantType

from tests.differential.reference import (
    ref_composition,
    ref_conditional,
    ref_negative,
    ref_ordering,
    ref_state,
    ref_statistical,
    ref_tool_selection,
)
from tests.property.strategies import invariant_spec, normalized_trace


_REF = {
    InvariantType.ORDERING: ref_ordering,
    InvariantType.CONDITIONAL: ref_conditional,
    InvariantType.NEGATIVE: ref_negative,
    InvariantType.STATE: ref_state,
    InvariantType.COMPOSITION: ref_composition,
    InvariantType.TOOL_SELECTION: ref_tool_selection,
    InvariantType.STATISTICAL: ref_statistical,
}


def _production(spec, trace) -> CheckOutcome:
    """Use check_trace so CheckerError converts to NOT_APPLICABLE consistently
    with how the streaming detector treats it."""
    return check_trace([spec], trace)[0].outcome


def _diff(spec, trace) -> tuple[CheckOutcome, CheckOutcome]:
    prod = _production(spec, trace)
    ref_fn = _REF.get(spec.type)
    ref = ref_fn(spec, trace) if ref_fn else CheckOutcome.NOT_APPLICABLE
    return prod, ref


# ---- per-type differential tests ---------------------------------------


@given(spec=invariant_spec(type_=InvariantType.ORDERING), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_ordering_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, (
        f"ordering mismatch: prod={prod}, ref={ref}, spec={spec}, "
        f"tools={[s.tool for s in trace.steps if hasattr(s, 'tool')]}"
    )


@given(spec=invariant_spec(type_=InvariantType.CONDITIONAL), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_conditional_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"conditional mismatch: prod={prod}, ref={ref}"


@given(spec=invariant_spec(type_=InvariantType.NEGATIVE), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_negative_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"negative mismatch: prod={prod}, ref={ref}"


@given(spec=invariant_spec(type_=InvariantType.STATE), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_state_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"state mismatch: prod={prod}, ref={ref}"


@given(spec=invariant_spec(type_=InvariantType.COMPOSITION), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_composition_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"composition mismatch: prod={prod}, ref={ref}"


@given(spec=invariant_spec(type_=InvariantType.TOOL_SELECTION), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_tool_selection_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"tool_selection mismatch: prod={prod}, ref={ref}"


@given(spec=invariant_spec(type_=InvariantType.STATISTICAL), trace=normalized_trace(max_steps=20))
@settings(max_examples=200, deadline=2000, suppress_health_check=[HealthCheck.too_slow])
def test_statistical_matches_reference(spec, trace) -> None:
    prod, ref = _diff(spec, trace)
    assert prod == ref, f"statistical mismatch: prod={prod}, ref={ref}"
